AWSTemplateFormatVersion: 2010-09-09
Description: 'todo'
Parameters:
  S3Bucket:
    Type: String
    Description: The S3Bucket where the lambda zip file can be found
  S3Key:
    Type: String
    Description: The file name of the lambda zip file
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'koel-storage'
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - s3.amazonaws.com
            Action:
              - sts:AssumeRole
  LambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn: LambdaRole
    Properties:
      Handler: 'main.handler'
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.6
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
